# Generated by Django 5.2.7 on 2025-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_rating', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('matched', 'Matched'), ('expired', 'Expired')], default='waiting', max_length=20)),
            ],
            options={
                'db_table': 'matchmaking_queue',
                'ordering': ['joined_at'],
            },
        ),
    ]
