# Generated by Django 5.2.7 on 2025-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('local', 'Local Multiplayer'), ('online', 'Online Match'), ('ai', 'vs AI')], max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('black_win', 'Black Wins'), ('white_win', 'White Wins'), ('draw', 'Draw'), (None, 'Ongoing')], max_length=20, null=True)),
                ('board_state', models.JSONField(default=list)),
                ('move_history', models.JSONField(default=list)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('winning_line', models.JSONField(blank=True, null=True)),
                ('black_elo_before', models.IntegerField(blank=True, null=True)),
                ('white_elo_before', models.IntegerField(blank=True, null=True)),
                ('black_elo_change', models.IntegerField(blank=True, null=True)),
                ('white_elo_change', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-created_at'],
            },
        ),
    ]
